import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button, ColorSchemeScript, Flex, MantineProvider, colorsTuple } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider
          theme={{
            colors: {
              appPurple: ['#F2EBF9', '#E5D5FA', '#D1B4F8', '#BD93F7', '#9854F6', '#541F9D', '#000000', '#000000', '#000000', '#000000'],
              appYellow: ['#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005'],
              appGray: ['#F5F5F6', '#EAEBED', '#D5D6DC', '#ACADB9', '#7B7C88', '#000000', '#000000', '#000000', '#000000', '#000000']
            }
          }}
        >
          <Flex>
            <nav
              className="w-20">
              <Flex>
                <Button>Movies</Button>
                <Button>Rated Movies</Button>
              </Flex>
            </nav>
            <main className={inter.className}>{children}</main>
          </Flex>

        </MantineProvider>
      </body>
    </html>
  );
}
