import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css"
import { AppShell, ColorSchemeScript, Flex, MantineProvider } from "@mantine/core";
import { Navbar } from "@/app/ui/navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <MantineProvider
          theme={{
            colors: {
              appPurple: ['#F2EBF9', '#E5D5FA', '#D1B4F8', '#BD93F7', '#9854F6', '#541F9D', '#000000', '#000000', '#000000', '#000000'],
              appYellow: ['#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005', '#FAB005'],
              appGray: ['#F5F5F6', '#EAEBED', '#D5D6DC', '#ACADB9', '#7B7C88', '#000000', '#000000', '#000000', '#000000', '#000000']
            }
          }}
        >
          <Navbar />
          <Flex>
            <main className={inter.className}>{children}</main>
          </Flex>
        </MantineProvider>
      </body>
    </html>
  );
}
